version: '3.8'

services:
  dogpostgres:
    image: postgres:latest
    container_name: dogpostgres
    environment:
      POSTGRES_DB: dogdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  dogapi:
    build:
      context: ./
    ports:
      - "8080:8080"