version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: dogdb
      POSTGRES_USER: primea
      POSTGRES_PASSWORD: primea
    ports:
      - "5432:5432"





