postgresConfiguration:
    host:  ${HOST:localhost}
    port: ${PORT:5432}
    database: ${DATABASE:dogdb}
    username: ${USERNAME:test}
    password: ${PASSWORD:test}
    table: ${TABLE:dog}
    driver: ${DRIVER:"org.postgresql.Driver"}


spring:
    sql:
        init:
            mode: always
    jpa:
        defer-datasource-initialization: true