postgresConfiguration:
    host: localhost #${HOST:localhost}
    port: 5432 #${PORT:5432}
    database: dogdb #${DATABASE:dogdb}
    username: primea #${USERNAME:primea}
    password: primea #${PASSWORD:primea}
    table: dog # ${TABLE:dog}
    driver: org.postgresql.Driver #${DRIVER:"org.postgresql.Driver"}


spring:
    sql:
        init:
            mode: always

    jpa:
        defer-datasource-initialization: true